name: SimpleTimer
version: '${project.version}'
main: de.gamingfelin.simpletimer.SimpleTimer
api-version: 1.19
commands:
  timer:
    description: Simple Timer
  timerc:
    description: Simple Timer Config